test:
  image: alpine:latest
  script:
    - apk update && apk add build-base cmake ruby
    - cmake -B build tests
    - cmake --build build --parallel
    - ctest --test-dir build --output-on-error
