test:
  image: alpine:latest
  script:
    - apk update && apk add build-base cmake ruby
    - cmake -B build tests
    - cmake --build build --parallel
    - ctest --test-dir build --output-on-error

build:
  image: harrymander/ence464-arm-toolchain:latest
  script:
    - |
      cmake -B build \
      --toolchain cmake/tm4c.cmake \
      -DENABLE_PROGRAM_TARGETS=off \
      -DBUILD_DEMOS=off \
      target
    - cmake --build build --parallel --target fitness-tracker
    - mv build/src/fitness-tracker .
  artifacts:
    name: fitness-tracker
    paths:
      - fitness-tracker
